### ISSUE TITLE
[Hack Pod] Copilot for getting started with Actions 

### ISSUE THREAD

**Issue by manishapriya94** [OpenSourceFellows/open-source-mentorship#41]
### Spec
User story: what kind of Action would make people more welcome to this project with either
- helpful prompts or reminders 
- help us communicate better 
- coordinate some of the project's details

### Resources: 
- [What is an Action ](https://docs.github.com/en/actions)
- [Our current workflows ](https://github.com/ProgramEquity/amplify/actions)
- [Getting started with GitHub Actions](https://docs.github.com/en/actions/quickstart)
- How to use Copilot to write your action [recording](https://www.notion.so/programequity/GitHub-workflows-with-Codespaces-Copilot-655b6cdca0344daf9e2bcd351e53b24d)
- If you're done with your task and want to suggest one of your own, check out [marketplace ](https://github.com/marketplace?type=actions)

### Tasks: 
**Collaboration** : Including communication and engagement tools 
- [ ] 🎢 Welcome messages by @Alex-is-Gonzalez ProgramEquity/amplify#520 
- [ ] 🛒 Awake Yet Action by @abirismyname ProgramEquity/amplify#447
- [ ] 🎢 [labeler](https://github.com/actions/labeler)
- [ ] 🛒 [Spellcheck](https://github.com/austenstone/spellchecker-cli-action-summary) by @austenstone! 

------------------------
### Target Date: 
2022-02-22 
Maintainers for reference are assigned 
Pair Hour Mentors: assign yourself in each task when its ready to review

**Comment by JamesMGreene** [comment]
Could someone with write permissions kindly unassign me from this issue when they get a chance? Thanks! 🙏🏻
